/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SystemsRouteImport } from './routes/systems'
import { Route as RegionsRouteImport } from './routes/regions'
import { Route as ProcessNamesRouteImport } from './routes/process-names'
import { Route as HostnamesRouteImport } from './routes/hostnames'
import { Route as AppnamesRouteImport } from './routes/appnames'
import { Route as IndexRouteImport } from './routes/index'

const SystemsRoute = SystemsRouteImport.update({
  id: '/systems',
  path: '/systems',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionsRoute = RegionsRouteImport.update({
  id: '/regions',
  path: '/regions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessNamesRoute = ProcessNamesRouteImport.update({
  id: '/process-names',
  path: '/process-names',
  getParentRoute: () => rootRouteImport,
} as any)
const HostnamesRoute = HostnamesRouteImport.update({
  id: '/hostnames',
  path: '/hostnames',
  getParentRoute: () => rootRouteImport,
} as any)
const AppnamesRoute = AppnamesRouteImport.update({
  id: '/appnames',
  path: '/appnames',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appnames': typeof AppnamesRoute
  '/hostnames': typeof HostnamesRoute
  '/process-names': typeof ProcessNamesRoute
  '/regions': typeof RegionsRoute
  '/systems': typeof SystemsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appnames': typeof AppnamesRoute
  '/hostnames': typeof HostnamesRoute
  '/process-names': typeof ProcessNamesRoute
  '/regions': typeof RegionsRoute
  '/systems': typeof SystemsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/appnames': typeof AppnamesRoute
  '/hostnames': typeof HostnamesRoute
  '/process-names': typeof ProcessNamesRoute
  '/regions': typeof RegionsRoute
  '/systems': typeof SystemsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appnames'
    | '/hostnames'
    | '/process-names'
    | '/regions'
    | '/systems'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appnames'
    | '/hostnames'
    | '/process-names'
    | '/regions'
    | '/systems'
  id:
    | '__root__'
    | '/'
    | '/appnames'
    | '/hostnames'
    | '/process-names'
    | '/regions'
    | '/systems'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppnamesRoute: typeof AppnamesRoute
  HostnamesRoute: typeof HostnamesRoute
  ProcessNamesRoute: typeof ProcessNamesRoute
  RegionsRoute: typeof RegionsRoute
  SystemsRoute: typeof SystemsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/systems': {
      id: '/systems'
      path: '/systems'
      fullPath: '/systems'
      preLoaderRoute: typeof SystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regions': {
      id: '/regions'
      path: '/regions'
      fullPath: '/regions'
      preLoaderRoute: typeof RegionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process-names': {
      id: '/process-names'
      path: '/process-names'
      fullPath: '/process-names'
      preLoaderRoute: typeof ProcessNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hostnames': {
      id: '/hostnames'
      path: '/hostnames'
      fullPath: '/hostnames'
      preLoaderRoute: typeof HostnamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appnames': {
      id: '/appnames'
      path: '/appnames'
      fullPath: '/appnames'
      preLoaderRoute: typeof AppnamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppnamesRoute: AppnamesRoute,
  HostnamesRoute: HostnamesRoute,
  ProcessNamesRoute: ProcessNamesRoute,
  RegionsRoute: RegionsRoute,
  SystemsRoute: SystemsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
